import type {
  Campaign, Customer, Call, User, Role, AuditLog, Notification, Integration,
  DailyMetric, LocationMetric, BrandMetric, FunnelStage, TranscriptSegment
} from '@/types'

// ─── Campaigns ─────────────────────────────────────────────────────────────────

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Toyota HiLux Service Reminder Q2 2026',
    type: 'service_reminder',
    status: 'active',
    brand: 'Toyota',
    location: 'Keysborough',
    totalContacts: 1240,
    contactsAttempted: 876,
    contactsReached: 612,
    bookings: 134,
    conversions: 98,
    conversionRate: 15.9,
    answerRate: 69.9,
    startDate: '2026-06-01',
    endDate: '2026-06-30',
    scheduledTime: '10:00 AM - 6:00 PM',
    maxAttempts: 3,
    attemptsCompleted: 876,
    revenueImpact: 294000,
    createdAt: '2026-05-28T09:00:00Z',
    updatedAt: '2026-06-28T14:22:00Z',
    aiAgentName: 'Aria',
    script: 'Hi, this is Aria calling from Patterson Cheney Toyota Keysborough...',
    tags: ['high-value', 'service', 'Q2'],
  },
  {
    id: 'camp-002',
    name: 'Mercedes GLC Upgrade Offer — June',
    type: 'upgrade_offer',
    status: 'active',
    brand: 'Mercedes-Benz',
    location: 'Berwick',
    totalContacts: 480,
    contactsAttempted: 360,
    contactsReached: 228,
    bookings: 42,
    conversions: 31,
    conversionRate: 13.6,
    answerRate: 63.3,
    startDate: '2026-06-10',
    endDate: '2026-07-10',
    scheduledTime: '11:00 AM - 7:00 PM',
    maxAttempts: 3,
    attemptsCompleted: 360,
    revenueImpact: 1116000,
    createdAt: '2026-06-08T11:30:00Z',
    updatedAt: '2026-06-28T10:00:00Z',
    aiAgentName: 'Aria',
    script: 'Good morning, I\'m Aria from Patterson Cheney Mercedes-Benz...',
    tags: ['premium', 'upgrade', 'mercedes'],
  },
  {
    id: 'camp-003',
    name: 'Isuzu D-Max Finance Renewal',
    type: 'finance_renewal',
    status: 'paused',
    brand: 'Isuzu UTE',
    location: 'Dandenong',
    totalContacts: 320,
    contactsAttempted: 210,
    contactsReached: 144,
    bookings: 28,
    conversions: 19,
    conversionRate: 13.2,
    answerRate: 68.6,
    startDate: '2026-05-20',
    endDate: '2026-06-20',
    scheduledTime: '09:00 AM - 5:00 PM',
    maxAttempts: 2,
    attemptsCompleted: 210,
    revenueImpact: 570000,
    createdAt: '2026-05-15T08:00:00Z',
    updatedAt: '2026-06-15T16:40:00Z',
    aiAgentName: 'Max',
    script: 'Hi there, this is Max calling from Patterson Cheney Isuzu...',
    tags: ['finance', 'isuzu', 'renewal'],
  },
  {
    id: 'camp-004',
    name: 'RAV4 Hybrid Re-engagement — Churned',
    type: 'reengagement',
    status: 'completed',
    brand: 'Toyota',
    location: 'Chadstone',
    totalContacts: 650,
    contactsAttempted: 650,
    contactsReached: 410,
    bookings: 88,
    conversions: 61,
    conversionRate: 14.9,
    answerRate: 63.1,
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    scheduledTime: '10:00 AM - 6:00 PM',
    maxAttempts: 3,
    attemptsCompleted: 650,
    revenueImpact: 183000,
    createdAt: '2026-04-28T10:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
    aiAgentName: 'Aria',
    script: 'Hi, I\'m Aria from Patterson Cheney Chadstone Toyota...',
    tags: ['reengagement', 'hybrid', 'completed'],
  },
  {
    id: 'camp-005',
    name: 'Mahindra Scorpio-N Launch Outreach',
    type: 'upgrade_offer',
    status: 'scheduled',
    brand: 'Mahindra',
    location: 'Werribee',
    totalContacts: 290,
    contactsAttempted: 0,
    contactsReached: 0,
    bookings: 0,
    conversions: 0,
    conversionRate: 0,
    answerRate: 0,
    startDate: '2026-07-01',
    endDate: '2026-07-31',
    scheduledTime: '10:00 AM - 5:00 PM',
    maxAttempts: 3,
    attemptsCompleted: 0,
    revenueImpact: 0,
    createdAt: '2026-06-25T14:00:00Z',
    updatedAt: '2026-06-25T14:00:00Z',
    aiAgentName: 'Aria',
    script: 'Hi, this is Aria from Werribee Mahindra...',
    tags: ['launch', 'mahindra', 'new-model'],
  },
  {
    id: 'camp-006',
    name: 'Mercedes C-Class Winter Service Drive',
    type: 'service_reminder',
    status: 'draft',
    brand: 'Mercedes-Benz',
    location: 'Brighton',
    totalContacts: 380,
    contactsAttempted: 0,
    contactsReached: 0,
    bookings: 0,
    conversions: 0,
    conversionRate: 0,
    answerRate: 0,
    startDate: '2026-07-15',
    endDate: '2026-08-15',
    scheduledTime: '10:00 AM - 6:00 PM',
    maxAttempts: 2,
    attemptsCompleted: 0,
    revenueImpact: 0,
    createdAt: '2026-06-28T09:00:00Z',
    updatedAt: '2026-06-28T09:00:00Z',
    aiAgentName: 'Aria',
    script: 'Good morning, I\'m Aria from Patterson Cheney Mercedes-Benz Brighton...',
    tags: ['winter', 'service', 'mercedes', 'draft'],
  },
]

// ─── Customers ─────────────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    firstName: 'James',
    lastName: 'Nguyen',
    fullName: 'James Nguyen',
    email: 'james.nguyen@gmail.com',
    phone: '(03) 9789 2341',
    mobilePhone: '0412 345 678',
    address: '14 Acacia Court',
    suburb: 'Keysborough',
    state: 'VIC',
    postcode: '3173',
    status: 'active',
    upgradeScore: 5,
    vehicle: {
      id: 'veh-001',
      make: 'Toyota',
      model: 'HiLux',
      year: 2021,
      variant: 'SR5 4x4 Double Cab',
      color: 'Graphite',
      vin: 'MR0FR8CD9M0123456',
      regPlate: 'ABC-123',
      odometer: 68200,
      purchaseDate: '2021-04-15',
      lastServiceDate: '2025-10-20',
      nextServiceDue: '2026-04-20',
      financeEndDate: '2026-10-15',
      warrantyExpiry: '2027-04-15',
    },
    previousVehicles: [],
    assignedDealership: 'Patterson Cheney Toyota Keysborough',
    brand: 'Toyota',
    totalSpend: 72400,
    lifetimeValue: 98000,
    campaignHistory: ['camp-001'],
    lastContactDate: '2026-06-22',
    preferredContactTime: 'Morning',
    notes: 'High-value customer, interested in new HiLux Rogue upgrade.',
    createdAt: '2021-04-15T10:00:00Z',
    doNotCall: false,
    tags: ['high-value', 'upgrade-ready', 'finance-ending'],
  },
  {
    id: 'cust-002',
    firstName: 'Sarah',
    lastName: 'Thompson',
    fullName: 'Sarah Thompson',
    email: 's.thompson@hotmail.com',
    phone: '(03) 9554 8812',
    mobilePhone: '0433 876 543',
    address: '3/82 Canterbury Road',
    suburb: 'Berwick',
    state: 'VIC',
    postcode: '3806',
    status: 'active',
    upgradeScore: 4,
    vehicle: {
      id: 'veh-002',
      make: 'Mercedes-Benz',
      model: 'GLC',
      year: 2022,
      variant: '300 SUV AMG Line',
      color: 'Polar White',
      vin: 'WDC2539571F456789',
      regPlate: 'XYZ-789',
      odometer: 42100,
      purchaseDate: '2022-03-10',
      lastServiceDate: '2025-09-10',
      nextServiceDue: '2026-03-10',
      financeEndDate: '2027-03-10',
      warrantyExpiry: '2027-03-10',
    },
    previousVehicles: [],
    assignedDealership: 'Mercedes-Benz Berwick',
    brand: 'Mercedes-Benz',
    totalSpend: 94500,
    lifetimeValue: 142000,
    campaignHistory: ['camp-002'],
    lastContactDate: '2026-06-18',
    preferredContactTime: 'Afternoon',
    notes: 'Expressed interest in GLC 43 AMG at last service.',
    createdAt: '2022-03-10T09:30:00Z',
    doNotCall: false,
    tags: ['premium', 'upgrade-interest', 'amg-prospect'],
  },
  {
    id: 'cust-003',
    firstName: 'Michael',
    lastName: 'Patel',
    fullName: 'Michael Patel',
    email: 'mpatel@businessmail.com.au',
    phone: '(03) 9702 3341',
    mobilePhone: '0421 567 890',
    address: '56 Enterprise Drive',
    suburb: 'Dandenong',
    state: 'VIC',
    postcode: '3175',
    status: 'active',
    upgradeScore: 4,
    vehicle: {
      id: 'veh-003',
      make: 'Isuzu',
      model: 'D-Max',
      year: 2020,
      variant: 'X-Terrain 4x4 Crew Cab',
      color: 'Obsidian Grey',
      vin: 'JA4AP3AU0LZ234567',
      regPlate: 'MNO-456',
      odometer: 91000,
      purchaseDate: '2020-08-22',
      lastServiceDate: '2025-08-22',
      nextServiceDue: '2026-02-22',
      financeEndDate: '2025-08-22',
      warrantyExpiry: '2025-08-22',
    },
    previousVehicles: [],
    assignedDealership: 'Patterson Cheney Isuzu Dandenong',
    brand: 'Isuzu UTE',
    totalSpend: 58700,
    lifetimeValue: 85000,
    campaignHistory: ['camp-003'],
    lastContactDate: '2026-06-10',
    preferredContactTime: 'Morning',
    notes: 'Finance ended. Fleet buyer — owns 2 additional D-Max in business fleet.',
    createdAt: '2020-08-22T11:00:00Z',
    doNotCall: false,
    tags: ['fleet', 'finance-ended', 'commercial'],
  },
  {
    id: 'cust-004',
    firstName: 'Lisa',
    lastName: 'Moran',
    fullName: 'Lisa Moran',
    email: 'lisamoran@me.com',
    phone: '(03) 9857 4421',
    mobilePhone: '0409 123 456',
    address: '28 Royal Parade',
    suburb: 'Chadstone',
    state: 'VIC',
    postcode: '3148',
    status: 'active',
    upgradeScore: 3,
    vehicle: {
      id: 'veh-004',
      make: 'Toyota',
      model: 'RAV4',
      year: 2021,
      variant: 'Cruiser Hybrid AWD',
      color: 'Graphite',
      vin: 'JTMDH3FV4M5123456',
      regPlate: 'GHI-321',
      odometer: 54300,
      purchaseDate: '2021-01-20',
      lastServiceDate: '2025-07-20',
      nextServiceDue: '2026-01-20',
      financeEndDate: undefined,
      warrantyExpiry: '2028-01-20',
    },
    previousVehicles: [],
    assignedDealership: 'Chadstone Toyota',
    brand: 'Toyota',
    totalSpend: 61200,
    lifetimeValue: 72000,
    campaignHistory: ['camp-004'],
    lastContactDate: '2026-05-28',
    preferredContactTime: 'Evening',
    notes: 'Booked a service after last campaign call. Happy customer.',
    createdAt: '2021-01-20T14:00:00Z',
    doNotCall: false,
    tags: ['hybrid', 'service-booked'],
  },
  {
    id: 'cust-005',
    firstName: 'David',
    lastName: 'Wilson',
    fullName: 'David Wilson',
    email: 'david.wilson@outlook.com',
    phone: '(03) 9741 8832',
    mobilePhone: '0418 234 567',
    address: '11 Peel Street',
    suburb: 'Werribee',
    state: 'VIC',
    postcode: '3030',
    status: 'prospect',
    upgradeScore: 2,
    vehicle: {
      id: 'veh-005',
      make: 'Mahindra',
      model: 'Pik-Up',
      year: 2019,
      variant: 'S10+ 4WD Auto',
      color: 'Red',
      vin: 'MA1YB2DFXKM789012',
      regPlate: 'DEF-654',
      odometer: 112000,
      purchaseDate: '2019-06-12',
      lastServiceDate: '2024-12-12',
      nextServiceDue: '2025-06-12',
      financeEndDate: undefined,
      warrantyExpiry: '2024-06-12',
    },
    previousVehicles: [],
    assignedDealership: 'Werribee Mahindra',
    brand: 'Mahindra',
    totalSpend: 38900,
    lifetimeValue: 45000,
    campaignHistory: [],
    lastContactDate: '2026-01-15',
    preferredContactTime: 'Afternoon',
    notes: 'Vehicle is aging. May be interested in Scorpio-N launch.',
    createdAt: '2019-06-12T09:00:00Z',
    doNotCall: false,
    tags: ['high-mileage', 'prospect'],
  },
  {
    id: 'cust-006',
    firstName: 'Emma',
    lastName: 'Chen',
    fullName: 'Emma Chen',
    email: 'emma.chen@gmail.com',
    phone: '(03) 9593 7712',
    mobilePhone: '0425 678 901',
    address: '8 Marine Parade',
    suburb: 'Brighton',
    state: 'VIC',
    postcode: '3186',
    status: 'active',
    upgradeScore: 5,
    vehicle: {
      id: 'veh-006',
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2022,
      variant: 'C 200 Sedan AMG Line',
      color: 'Selenite Grey',
      vin: 'WDD2050561R890123',
      regPlate: 'JKL-987',
      odometer: 38700,
      purchaseDate: '2022-09-15',
      lastServiceDate: '2025-09-15',
      nextServiceDue: '2026-03-15',
      financeEndDate: '2026-09-15',
      warrantyExpiry: '2027-09-15',
    },
    previousVehicles: [],
    assignedDealership: 'Mercedes-Benz Brighton',
    brand: 'Mercedes-Benz',
    totalSpend: 86200,
    lifetimeValue: 168000,
    campaignHistory: [],
    lastContactDate: '2026-06-28',
    preferredContactTime: 'Morning',
    notes: 'Long-term customer — 3rd Mercedes. Finance ending Sep 26. Prime upgrade candidate.',
    createdAt: '2018-03-01T10:00:00Z',
    doNotCall: false,
    tags: ['vip', 'repeat-buyer', 'finance-ending', 'upgrade-ready'],
  },
]

// ─── Calls ─────────────────────────────────────────────────────────────────────

export const mockTranscript: TranscriptSegment[] = [
  {
    id: 'seg-001',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'Good morning, may I please speak with James Nguyen?',
    timestamp: 0,
    sentiment: 'neutral',
    confidence: 0.98,
  },
  {
    id: 'seg-002',
    speaker: 'customer',
    speakerName: 'James Nguyen',
    text: 'Speaking, who\'s this?',
    timestamp: 3,
    sentiment: 'neutral',
    confidence: 0.94,
  },
  {
    id: 'seg-003',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'Hi James, this is Aria calling from Patterson Cheney Toyota Keysborough. How are you today?',
    timestamp: 5,
    sentiment: 'positive',
    confidence: 0.99,
  },
  {
    id: 'seg-004',
    speaker: 'customer',
    speakerName: 'James Nguyen',
    text: 'Yeah, good thanks. What\'s this about?',
    timestamp: 10,
    sentiment: 'neutral',
    confidence: 0.91,
  },
  {
    id: 'seg-005',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'I\'m reaching out because your 2021 HiLux SR5 is coming up for its next scheduled service in April. I wanted to check in and see if you\'d like to book it in at a time that suits you.',
    timestamp: 15,
    sentiment: 'positive',
    confidence: 0.97,
  },
  {
    id: 'seg-006',
    speaker: 'customer',
    speakerName: 'James Nguyen',
    text: 'Oh yeah, I\'ve been meaning to sort that. What\'s available?',
    timestamp: 28,
    sentiment: 'positive',
    confidence: 0.93,
  },
  {
    id: 'seg-007',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'We have availability next Tuesday the 2nd of April from 8am, or Thursday the 4th from 10am. Which would work better for you?',
    timestamp: 32,
    sentiment: 'positive',
    confidence: 0.98,
  },
  {
    id: 'seg-008',
    speaker: 'customer',
    speakerName: 'James Nguyen',
    text: 'Thursday at 10 works. Do you have loaners available?',
    timestamp: 41,
    sentiment: 'positive',
    confidence: 0.95,
  },
  {
    id: 'seg-009',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'Absolutely, I\'ll make a note to request a loan vehicle for you. I\'ll book Thursday 4th April at 10am. You\'ll receive an SMS confirmation shortly. Is there anything else I can help with today?',
    timestamp: 46,
    sentiment: 'positive',
    confidence: 0.99,
  },
  {
    id: 'seg-010',
    speaker: 'customer',
    speakerName: 'James Nguyen',
    text: 'No that\'s great, thanks Aria.',
    timestamp: 58,
    sentiment: 'positive',
    confidence: 0.97,
  },
  {
    id: 'seg-011',
    speaker: 'agent',
    speakerName: 'Aria (AI Agent)',
    text: 'Wonderful! We\'ll see you Thursday. Have a great day James, take care.',
    timestamp: 61,
    sentiment: 'positive',
    confidence: 0.99,
  },
]

export const mockCalls: Call[] = [
  {
    id: 'call-001',
    customerId: 'cust-001',
    customerName: 'James Nguyen',
    customerPhone: '0412 345 678',
    campaignId: 'camp-001',
    campaignName: 'Toyota HiLux Service Reminder Q2 2026',
    direction: 'outbound',
    outcome: 'booked',
    sentiment: 'positive',
    duration: 68,
    startTime: '2026-06-22T10:14:00Z',
    endTime: '2026-06-22T10:15:08Z',
    recording: { url: '/recordings/call-001.mp3', duration: 68, fileSize: 1024000 },
    transcript: mockTranscript,
    aiSummary: 'Customer James Nguyen confirmed a service booking for his 2021 Toyota HiLux SR5. Booked Thursday 4th April at 10:00am with loan vehicle requested. Customer was receptive and friendly. No objections raised.',
    keyExtractions: {
      bookingDate: '2026-04-04',
      bookingTime: '10:00 AM',
      vehicleInterest: '2021 Toyota HiLux SR5',
      objections: [],
      nextSteps: ['Send SMS confirmation', 'Arrange loan vehicle'],
      dealValue: 1800,
    },
    confidenceScore: 0.97,
    agentName: 'Aria',
    dealershipLocation: 'Keysborough',
    brand: 'Toyota',
    createdAt: '2026-06-22T10:15:08Z',
  },
  {
    id: 'call-002',
    customerId: 'cust-002',
    customerName: 'Sarah Thompson',
    customerPhone: '0433 876 543',
    campaignId: 'camp-002',
    campaignName: 'Mercedes GLC Upgrade Offer — June',
    direction: 'outbound',
    outcome: 'callback_requested',
    sentiment: 'positive',
    duration: 94,
    startTime: '2026-06-18T14:32:00Z',
    endTime: '2026-06-18T14:33:34Z',
    recording: { url: '/recordings/call-002.mp3', duration: 94, fileSize: 1536000 },
    transcript: [],
    aiSummary: 'Sarah expressed interest in upgrading to the GLC 43 AMG but requested a callback next week when her husband is available to discuss. Scheduled follow-up for 25 June at 2pm.',
    keyExtractions: {
      bookingDate: '2026-06-25',
      bookingTime: '2:00 PM',
      vehicleInterest: 'GLC 43 AMG',
      objections: ['Needs husband to be present for decision'],
      nextSteps: ['Call back 25 June at 2pm', 'Send GLC 43 AMG brochure via email'],
      dealValue: 142000,
    },
    confidenceScore: 0.91,
    agentName: 'Aria',
    dealershipLocation: 'Berwick',
    brand: 'Mercedes-Benz',
    createdAt: '2026-06-18T14:33:34Z',
  },
  {
    id: 'call-003',
    customerId: 'cust-003',
    customerName: 'Michael Patel',
    customerPhone: '0421 567 890',
    campaignId: 'camp-003',
    campaignName: 'Isuzu D-Max Finance Renewal',
    direction: 'outbound',
    outcome: 'not_interested',
    sentiment: 'neutral',
    duration: 42,
    startTime: '2026-06-10T09:48:00Z',
    endTime: '2026-06-10T09:48:42Z',
    recording: { url: '/recordings/call-003.mp3', duration: 42, fileSize: 688000 },
    transcript: [],
    aiSummary: 'Michael stated he is currently reviewing options across multiple brands before committing. He was polite but not interested in proceeding now. Suggested calling back in 2 months.',
    keyExtractions: {
      objections: ['Reviewing multiple brands', 'Not ready to commit'],
      nextSteps: ['Schedule follow-up in 2 months — August 2026'],
      dealValue: 0,
    },
    confidenceScore: 0.88,
    agentName: 'Max',
    dealershipLocation: 'Dandenong',
    brand: 'Isuzu UTE',
    createdAt: '2026-06-10T09:48:42Z',
  },
  {
    id: 'call-004',
    customerId: 'cust-004',
    customerName: 'Lisa Moran',
    customerPhone: '0409 123 456',
    campaignId: 'camp-004',
    campaignName: 'RAV4 Hybrid Re-engagement — Churned',
    direction: 'outbound',
    outcome: 'booked',
    sentiment: 'positive',
    duration: 78,
    startTime: '2026-05-28T11:02:00Z',
    endTime: '2026-05-28T11:03:18Z',
    recording: { url: '/recordings/call-004.mp3', duration: 78, fileSize: 1280000 },
    transcript: [],
    aiSummary: 'Lisa confirmed a service booking for her RAV4 Hybrid. She mentioned she was very happy with the vehicle and asked about the new RAV4 GX variant pricing.',
    keyExtractions: {
      bookingDate: '2026-06-12',
      bookingTime: '9:00 AM',
      vehicleInterest: 'RAV4 GX (new model enquiry)',
      objections: [],
      nextSteps: ['Service booking confirmed', 'Send RAV4 GX pricing sheet'],
      dealValue: 1600,
    },
    confidenceScore: 0.94,
    agentName: 'Aria',
    dealershipLocation: 'Chadstone',
    brand: 'Toyota',
    createdAt: '2026-05-28T11:03:18Z',
  },
  {
    id: 'call-005',
    customerId: 'cust-006',
    customerName: 'Emma Chen',
    customerPhone: '0425 678 901',
    campaignId: 'camp-002',
    campaignName: 'Mercedes GLC Upgrade Offer — June',
    direction: 'outbound',
    outcome: 'no_answer',
    sentiment: 'neutral',
    duration: 0,
    startTime: '2026-06-28T10:20:00Z',
    endTime: '2026-06-28T10:20:28Z',
    recording: { url: '', duration: 0, fileSize: 0 },
    transcript: [],
    aiSummary: 'No answer. Voicemail not available. Will retry attempt 2.',
    keyExtractions: {},
    confidenceScore: 0,
    agentName: 'Aria',
    dealershipLocation: 'Brighton',
    brand: 'Mercedes-Benz',
    createdAt: '2026-06-28T10:20:28Z',
  },
]

// ─── Users ─────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'user-001',
    firstName: 'Alex',
    lastName: 'Harrison',
    fullName: 'Alex Harrison',
    email: 'alex.harrison@pattersoncheney.com.au',
    role: 'super_admin',
    status: 'active',
    dealership: 'Group HQ',
    brand: 'All Brands',
    lastLogin: '2026-06-28T09:12:00Z',
    createdAt: '2025-01-10T08:00:00Z',
    permissions: [],
    activityCount: 1842,
  },
  {
    id: 'user-002',
    firstName: 'Priya',
    lastName: 'Sharma',
    fullName: 'Priya Sharma',
    email: 'priya.sharma@pattersoncheney.com.au',
    role: 'admin',
    status: 'active',
    dealership: 'Toyota Keysborough',
    brand: 'Toyota',
    lastLogin: '2026-06-28T08:45:00Z',
    createdAt: '2025-03-22T09:00:00Z',
    permissions: [],
    activityCount: 743,
  },
  {
    id: 'user-003',
    firstName: 'Tom',
    lastName: 'Bradley',
    fullName: 'Tom Bradley',
    email: 'tom.bradley@pattersoncheney.com.au',
    role: 'manager',
    status: 'active',
    dealership: 'Mercedes-Benz Berwick',
    brand: 'Mercedes-Benz',
    lastLogin: '2026-06-27T16:30:00Z',
    createdAt: '2025-06-01T10:00:00Z',
    permissions: [],
    activityCount: 412,
  },
  {
    id: 'user-004',
    firstName: 'Jessica',
    lastName: 'Park',
    fullName: 'Jessica Park',
    email: 'jessica.park@pattersoncheney.com.au',
    role: 'agent',
    status: 'active',
    dealership: 'Isuzu Dandenong',
    brand: 'Isuzu UTE',
    lastLogin: '2026-06-28T07:55:00Z',
    createdAt: '2025-09-14T08:30:00Z',
    permissions: [],
    activityCount: 228,
  },
  {
    id: 'user-005',
    firstName: 'Mark',
    lastName: 'Sullivan',
    fullName: 'Mark Sullivan',
    email: 'mark.sullivan@pattersoncheney.com.au',
    role: 'viewer',
    status: 'inactive',
    dealership: 'Mahindra Werribee',
    brand: 'Mahindra',
    lastLogin: '2026-05-15T11:20:00Z',
    createdAt: '2025-11-03T09:00:00Z',
    permissions: [],
    activityCount: 89,
  },
]

export const mockRoles: Role[] = [
  {
    id: 'role-001',
    name: 'Super Admin',
    description: 'Full access to all features and settings across the entire platform.',
    userCount: 2,
    isSystemRole: true,
    createdAt: '2025-01-01T00:00:00Z',
    permissions: [
      { resource: 'campaigns', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'customers', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'calls', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'analytics', actions: ['view', 'export'] },
      { resource: 'users', actions: ['view', 'create', 'edit', 'delete'] },
      { resource: 'roles', actions: ['view', 'create', 'edit', 'delete'] },
      { resource: 'audit_logs', actions: ['view', 'export'] },
      { resource: 'settings', actions: ['view', 'edit'] },
      { resource: 'integrations', actions: ['view', 'edit'] },
      { resource: 'simulation', actions: ['view', 'create'] },
    ],
  },
  {
    id: 'role-002',
    name: 'Admin',
    description: 'Manage campaigns, customers, and view analytics for their dealership.',
    userCount: 5,
    isSystemRole: true,
    createdAt: '2025-01-01T00:00:00Z',
    permissions: [
      { resource: 'campaigns', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { resource: 'customers', actions: ['view', 'create', 'edit', 'export'] },
      { resource: 'calls', actions: ['view', 'export'] },
      { resource: 'analytics', actions: ['view', 'export'] },
      { resource: 'users', actions: ['view', 'create', 'edit'] },
      { resource: 'audit_logs', actions: ['view'] },
      { resource: 'settings', actions: ['view', 'edit'] },
      { resource: 'simulation', actions: ['view', 'create'] },
    ],
  },
  {
    id: 'role-003',
    name: 'Manager',
    description: 'View campaigns, customers, calls, and analytics. Can create campaigns.',
    userCount: 8,
    isSystemRole: true,
    createdAt: '2025-01-01T00:00:00Z',
    permissions: [
      { resource: 'campaigns', actions: ['view', 'create', 'edit'] },
      { resource: 'customers', actions: ['view', 'edit'] },
      { resource: 'calls', actions: ['view'] },
      { resource: 'analytics', actions: ['view'] },
      { resource: 'simulation', actions: ['view', 'create'] },
    ],
  },
  {
    id: 'role-004',
    name: 'Agent',
    description: 'View customers and calls. Read-only access to campaigns.',
    userCount: 24,
    isSystemRole: false,
    createdAt: '2025-03-15T10:00:00Z',
    permissions: [
      { resource: 'campaigns', actions: ['view'] },
      { resource: 'customers', actions: ['view'] },
      { resource: 'calls', actions: ['view'] },
    ],
  },
  {
    id: 'role-005',
    name: 'Viewer',
    description: 'Read-only access to campaigns and analytics.',
    userCount: 11,
    isSystemRole: false,
    createdAt: '2025-03-15T10:00:00Z',
    permissions: [
      { resource: 'campaigns', actions: ['view'] },
      { resource: 'analytics', actions: ['view'] },
    ],
  },
]

// ─── Audit Logs ────────────────────────────────────────────────────────────────

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    userId: 'user-001',
    userName: 'Alex Harrison',
    action: 'campaign_started',
    resource: 'Campaign',
    resourceId: 'camp-001',
    resourceName: 'Toyota HiLux Service Reminder Q2 2026',
    details: 'Campaign started with 1,240 contacts and 3 max attempts.',
    ipAddress: '203.24.188.14',
    userAgent: 'Chrome 126 / macOS',
    timestamp: '2026-06-01T09:02:00Z',
    severity: 'info',
  },
  {
    id: 'log-002',
    userId: 'user-002',
    userName: 'Priya Sharma',
    action: 'updated',
    resource: 'Campaign',
    resourceId: 'camp-001',
    resourceName: 'Toyota HiLux Service Reminder Q2 2026',
    details: 'Updated scheduled call window from 9am–5pm to 10am–6pm.',
    ipAddress: '203.24.188.22',
    userAgent: 'Safari 17 / macOS',
    timestamp: '2026-06-03T11:14:00Z',
    severity: 'info',
  },
  {
    id: 'log-003',
    userId: 'user-003',
    userName: 'Tom Bradley',
    action: 'created',
    resource: 'Campaign',
    resourceId: 'camp-002',
    resourceName: 'Mercedes GLC Upgrade Offer — June',
    details: 'New campaign created targeting 480 contacts.',
    ipAddress: '203.24.188.80',
    userAgent: 'Chrome 126 / Windows',
    timestamp: '2026-06-08T11:30:00Z',
    severity: 'info',
  },
  {
    id: 'log-004',
    userId: 'user-001',
    userName: 'Alex Harrison',
    action: 'campaign_paused',
    resource: 'Campaign',
    resourceId: 'camp-003',
    resourceName: 'Isuzu D-Max Finance Renewal',
    details: 'Campaign paused due to public holiday — Queen\'s Birthday weekend.',
    ipAddress: '203.24.188.14',
    userAgent: 'Chrome 126 / macOS',
    timestamp: '2026-06-09T08:55:00Z',
    severity: 'warning',
  },
  {
    id: 'log-005',
    userId: 'user-002',
    userName: 'Priya Sharma',
    action: 'exported',
    resource: 'Customer',
    resourceId: 'all',
    resourceName: 'Customer Export — All Active',
    details: 'Exported 1,240 customer records to CSV.',
    ipAddress: '203.24.188.22',
    userAgent: 'Safari 17 / macOS',
    timestamp: '2026-06-20T14:42:00Z',
    severity: 'warning',
  },
  {
    id: 'log-006',
    userId: 'user-001',
    userName: 'Alex Harrison',
    action: 'permission_changed',
    resource: 'User',
    resourceId: 'user-004',
    resourceName: 'Jessica Park',
    details: 'Role changed from Viewer to Agent.',
    ipAddress: '203.24.188.14',
    userAgent: 'Chrome 126 / macOS',
    timestamp: '2026-06-22T09:10:00Z',
    severity: 'critical',
  },
]

// ─── Notifications ─────────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    type: 'booking',
    title: 'New Booking — James Nguyen',
    message: 'Service booking confirmed for 4 Apr 2026 at 10:00am. Toyota HiLux SR5.',
    read: false,
    createdAt: '2026-06-22T10:15:00Z',
    actionUrl: '/calls/call-001',
    relatedId: 'call-001',
  },
  {
    id: 'notif-002',
    type: 'booking',
    title: 'New Booking — Lisa Moran',
    message: 'Service booking confirmed for 12 Jun 2026 at 9:00am. Toyota RAV4 Hybrid.',
    read: false,
    createdAt: '2026-05-28T11:03:00Z',
    actionUrl: '/calls/call-004',
    relatedId: 'call-004',
  },
  {
    id: 'notif-003',
    type: 'upgrade_alert',
    title: 'High Upgrade Score — Emma Chen',
    message: 'Emma Chen has an upgrade score of 5/5. Finance ends Sep 2026. Prime candidate.',
    read: false,
    createdAt: '2026-06-28T09:00:00Z',
    actionUrl: '/customers/cust-006',
    relatedId: 'cust-006',
  },
  {
    id: 'notif-004',
    type: 'campaign_complete',
    title: 'Campaign Completed — RAV4 Re-engagement',
    message: 'RAV4 Hybrid Re-engagement campaign completed. 61 conversions, $183K revenue impact.',
    read: true,
    createdAt: '2026-06-01T00:00:00Z',
    actionUrl: '/campaigns/camp-004',
    relatedId: 'camp-004',
  },
  {
    id: 'notif-005',
    type: 'warning',
    title: 'Low Answer Rate — D-Max Finance',
    message: 'Campaign answer rate dropped to 48% today. Consider adjusting call times.',
    read: true,
    createdAt: '2026-06-08T16:30:00Z',
    actionUrl: '/campaigns/camp-003',
    relatedId: 'camp-003',
  },
  {
    id: 'notif-006',
    type: 'error',
    title: 'Integration Error — Google Sheets',
    message: 'Google Sheets sync failed. Last successful sync: 2 hours ago. Check API credentials.',
    read: false,
    createdAt: '2026-06-28T12:00:00Z',
    actionUrl: '/integrations',
  },
]

// ─── Analytics ─────────────────────────────────────────────────────────────────

export const mockDailyMetrics: DailyMetric[] = [
  { date: 'Jun 1', calls: 120, answered: 84, booked: 18, converted: 14, revenue: 42000, answerRate: 70, conversionRate: 16.7 },
  { date: 'Jun 3', calls: 145, answered: 98, booked: 22, converted: 17, revenue: 51000, answerRate: 67.6, conversionRate: 17.3 },
  { date: 'Jun 5', calls: 132, answered: 90, booked: 19, converted: 14, revenue: 42000, answerRate: 68.2, conversionRate: 15.6 },
  { date: 'Jun 8', calls: 168, answered: 118, booked: 26, converted: 20, revenue: 60000, answerRate: 70.2, conversionRate: 16.9 },
  { date: 'Jun 10', calls: 89, answered: 58, booked: 11, converted: 8, revenue: 24000, answerRate: 65.2, conversionRate: 13.8 },
  { date: 'Jun 12', calls: 156, answered: 108, booked: 24, converted: 18, revenue: 54000, answerRate: 69.2, conversionRate: 16.7 },
  { date: 'Jun 15', calls: 178, answered: 124, booked: 28, converted: 22, revenue: 66000, answerRate: 69.7, conversionRate: 17.7 },
  { date: 'Jun 17', calls: 142, answered: 96, booked: 20, converted: 15, revenue: 45000, answerRate: 67.6, conversionRate: 15.6 },
  { date: 'Jun 19', calls: 165, answered: 114, booked: 25, converted: 19, revenue: 57000, answerRate: 69.1, conversionRate: 16.7 },
  { date: 'Jun 22', calls: 188, answered: 132, booked: 30, converted: 23, revenue: 69000, answerRate: 70.2, conversionRate: 17.4 },
  { date: 'Jun 24', calls: 152, answered: 104, booked: 22, converted: 17, revenue: 51000, answerRate: 68.4, conversionRate: 16.3 },
  { date: 'Jun 26', calls: 175, answered: 122, booked: 27, converted: 21, revenue: 63000, answerRate: 69.7, conversionRate: 17.2 },
  { date: 'Jun 28', calls: 94, answered: 66, booked: 14, converted: 11, revenue: 33000, answerRate: 70.2, conversionRate: 16.7 },
]

export const mockLocationMetrics: LocationMetric[] = [
  { location: 'Keysborough', calls: 1240, conversions: 98, revenue: 294000, answerRate: 69.9 },
  { location: 'Berwick', calls: 480, conversions: 31, revenue: 1116000, answerRate: 63.3 },
  { location: 'Chadstone', calls: 650, conversions: 61, revenue: 183000, answerRate: 63.1 },
  { location: 'Dandenong', calls: 320, conversions: 19, revenue: 570000, answerRate: 68.6 },
  { location: 'Brighton', calls: 280, conversions: 22, revenue: 792000, answerRate: 71.2 },
  { location: 'Werribee', calls: 190, conversions: 11, revenue: 82500, answerRate: 61.4 },
]

export const mockBrandMetrics: BrandMetric[] = [
  { brand: 'Toyota', campaigns: 4, calls: 1890, conversions: 159, revenue: 477000, avgUpgradeScore: 3.8 },
  { brand: 'Mercedes-Benz', campaigns: 3, calls: 760, conversions: 53, revenue: 1908000, avgUpgradeScore: 4.2 },
  { brand: 'Isuzu UTE', campaigns: 2, calls: 320, conversions: 19, revenue: 570000, avgUpgradeScore: 3.5 },
  { brand: 'Mahindra', campaigns: 1, calls: 190, conversions: 11, revenue: 82500, avgUpgradeScore: 2.8 },
]

export const mockFunnelData: FunnelStage[] = [
  { stage: 'Total Contacts', count: 3160, percentage: 100 },
  { stage: 'Attempted', count: 2096, percentage: 66.3 },
  { stage: 'Answered', count: 1384, percentage: 43.8 },
  { stage: 'Engaged', count: 892, percentage: 28.2 },
  { stage: 'Booked', count: 292, percentage: 9.2 },
  { stage: 'Converted', count: 242, percentage: 7.7 },
]

export const mockIntegrations: Integration[] = [
  { id: 'int-001', name: 'Google Sheets', description: 'Sync customer data from Google Sheets in real-time.', logo: 'sheets', status: 'error', lastSync: '2026-06-28T12:00:00Z' },
  { id: 'int-002', name: 'Retell AI', description: 'Power AI voice agents with Retell\'s conversational AI.', logo: 'retell', status: 'connected', lastSync: '2026-06-28T14:30:00Z' },
  { id: 'int-003', name: 'Vapi', description: 'Alternative voice AI provider for outbound calling.', logo: 'vapi', status: 'disconnected' },
  { id: 'int-004', name: 'Slack', description: 'Send booking notifications and alerts to Slack channels.', logo: 'slack', status: 'connected', lastSync: '2026-06-28T15:00:00Z' },
  { id: 'int-005', name: 'Microsoft Teams', description: 'Post campaign updates and alerts to Teams channels.', logo: 'teams', status: 'disconnected' },
  { id: 'int-006', name: 'Email (SMTP)', description: 'Send confirmation emails and summaries via SMTP.', logo: 'email', status: 'connected', lastSync: '2026-06-28T10:00:00Z' },
]
